site_name: Coding Interview Diary
site_description: Algorithms, patterns, and interview prep
# repo_url: "https://github.com/gregalletti/interview-prep"

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  hide_source_files: false # excludes markdown source files in output site and remove copy page button
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  icon: uil:diary # use the shadcn svg if not defined
  topbar_sections: true 
  katex_options:
    displayMode: true
    macros:
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"
  show_datetime: true 
  accent: "oklch(64.5% 0.246 16.439)" # NEW!

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - pymdownx.tabbed
  - pymdownx.blocks.tab

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
