site_name: Coding Interview Diary
site_description: Algorithms, patterns, and interview prep

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascript/katex.js
  - javascript/animations.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/animations.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

nav:
  - Home: index.md
  - Data Structures & Algorithms:
    - Arrays & Hashing: 
      - Overview: files/dsa/00_arrays/00_arrays.md
      - 🟢 Easy problems:
        - Contains Duplicate: files/dsa/00_arrays/01_arrays.md
        - Is Anagram: files/dsa/00_arrays/02_arrays.md
      - 🟡 Medium problems:
        - Group Anagrams: files/dsa/00_arrays/03_arrays.md
        - Product of Array Except Self: files/dsa/00_arrays/04_arrays.md
    - Two Pointers:
      - Introduction: files/dsa/01_two_pointers/00_two_pointers.md
      - 🟢 Easy problems:
        - Valid Palindrome: files/dsa/01_two_pointers/01_two_pointers.md
      - 🟡 Medium problems:
        - Container With Most Water: files/dsa/01_two_pointers/02_two_pointers.md
      - 🔴 Hard problems:
        - Trapping Rain Water: files/dsa/01_two_pointers/03_two_pointers.md
    - Stack:
      - Introduction: files/dsa/02_stack/00_stack.md
      - 🟢 Easy problems:
        - Valid Parentheses: files/dsa/02_stack/01_stack.md
    - Binary Search:
      - Introduction: files/dsa/03_binary_search/00_binary_search.md
    - Sliding Window:
      - Introduction: files/dsa/04_sliding_window/00_sliding_window.md
    - Linked List:
      - Introduction: files/dsa/05_linked_list/00_linked_list.md
    - Trees:
      - Introduction: files/dsa/06_trees/00_trees.md
    - Tries:
      - Introduction: files/dsa/07_tries/00_tries.md
    - Backtracking:
      - Introduction: files/dsa/08_backtracking/00_backtracking.md
    - Heap / Priority Queue:
      - Introduction: files/dsa/09_heap_priority_queue/00_heap_priority_queue.md
    - Graph:
      - Introduction: files/dsa/10_graph/00_graph.md
    - 1D Dynamic Programming:
      - Introduction: files/dsa/11_dynamic_programming/00_dynamic_programming.md
    - Interval / Line Sweep:
      - Introduction: files/dsa/12_interval_line_sweep/00_interval_line_sweep.md
    - Greedy:
      - Introduction: files/dsa/13_greedy/00_greedy.md
    - Advanced Graph:
      - Introduction: files/dsa/14_advanced_graph/00_advanced_graph.md
    - 2D Dynamic Programming:
      - Introduction: files/dsa/15_2d_dynamic_programming/00_2d_dynamic_programming.md
    - Bit Manipulation:
      - Introduction: files/dsa/16_bit_manipulation/00_bit_manipulation
    - Math:
      - Introduction: files/dsa/17_math/00_math.md
  - System Design:
    - Introduction: files/system_design/00_system_design.md
    - Design Patterns:
      - Introduction: files/system_design/01_design_patterns/00_design_patterns.md
    - Scalability:
      - Introduction: files/system_design/02_scalability/00_scalability.md
  - AI & ML:
    - Introduction: files/ai_ml/00_ai_ml.md
    - AI and Agents:
      - Introduction: files/ai_ml/00_ai_agents/00_ai_agents.md
    - Machine Learning:
      - Introduction: files/ai_ml/01_machine_learning/00_machine_learning.md
    - Deep Learning:
      - Introduction: files/ai_ml/02_deep_learning/00_deep_learning.md
  - Frontend Engineering:
    - JavaScript / TypeScript:
      - Introduction: files/frontend/00_javascript/00_javascript.md
      - Reduce: files/frontend/00_javascript/01_reduce.md
    - React:
      - Introduction: files/frontend/01_react/00_react.md